{

    "nodatafound": "Nenhum arquivo encontrado.",
    "retrievingdata": "Restaurando arquivos.",
    "datarestored": "Ultimo arquivo salvo restaurado.",
    "greyuser": "Apenas cargos acima de Segurança podem Utilizar o bot.",
    "bouncer": "O EhBot não pode mover pessoas quando utilizado por seguranças.",
    "online": "/me %%BOTNAME%% v%%VERSION%% online!",


    "welcome": "/me Bem-vindo, %%NAME%%",
    "welcomeback": "/me Bem-vindo de volta, %%NAME%%",
    "songknown": "/me @%%NAME%%, Esta musica esta no historico.",
    "timelimit": "/me @%%NAME%%, Sua musica tem duração maior do que %%MAXLENGTH%% minutos..",
    "permissionownsong": "/me :up: @%%NAME%% Tem permissão para tocar musicas maiores!",
    "isblacklisted": "/me Esta musica esta na %%BLACKLIST%% lista negra! Pulando...",


    "isopen": "/me @djs A roleta esta agora aberta! Digite !join para concorrer á uma recolocação na lista!",
    "winnerpicked": "/me Um ganhador foi escolhido! @%%NAME%% Foi levado para a posição %%POSITION%%.",

    "ball": "/me a pergunta de %%NAME%% foi: \"%%QUESTION%%\" e a resposta do %%BOTNAME%% é: \"%%RESPONSE%%\"",

    "notghosting": "[%%NAME1%%] %%NAME2%% não esta ghosting.",
    "ghosting": "[%%NAME1%%] %%NAME2%% está ghosting ou não está aqui.",

    "alreadyadding": "/me o Usuario ja foi adicionado! Posição do usuario mudada para %%POSITION%%.",
    "adding": "/me @%%NAME%% foi adicionado para a lista. posição atual: %%POSITION%%.",


    "usernotfound": "/me Usuario não encontrado.",
    "notdisconnected": "/me @%%NAME%% Não se desconectou durante meu tempo aqui.",
    "noposition": "/me Nenhuma ultima posição encontrada. a lista de espera precisa atualizar pelo menos uma vez para registrar a posição do usuario.",
    "toolongago": "/me a ultima saida de @%%NAME%% foi á muito tempo atras: %%TIME%%.",
    "valid": "/me @%%NAME%% desconecttou-se á %%TIME%% atras, e deveria estar na posição %%POSITION%%.",


    "warning1": "/me @%%NAME%%, você ficou AFK por %%TIME%%, Responda em 2 minutos, ou será retirado da lista.",
    "warning2": "/me @%%NAME%%, Você será removido se não responder.",
    "afkremove": "/me @%%NAME%%, Você foi kickado por ficar AFK por %%TIME%%. Você estava na posição %%POSITION%%. Fale no chat pelo menos a cada %%MAXIMUMAFK%% minutos se você quiser tocar alguma musica.",


    "caps": "/me @%%NAME%%, porfavor desative seu capslock.",
    "askskip": "/me @%%NAME%%, não pergunte por skips.",
    "spam": "/me @%%NAME%%, por favor, não faça spam.",
    "roomadvertising": "/me @%%NAME%%, não divulgue links para outras salas.",
    "adfly": "/me @%%NAME%%, por favor mude seu autowoot, recomendamos o Origem-Woot: http://origem-woot.com/",

    "validgiftags": "/me [@%%NAME%%] http://media.giphy.com/media/%%ID%%/giphy.gif [Tags: %%TAGS%%]",
    "invalidgiftags": "/me [@%%NAME%%] Invalid tags, try something different. [Tags: %%TAGS%%]",
    "validgifrandom": "/me [@%%NAME%%] http://media.giphy.com/media/%%ID%%/giphy.gif [Random GIF]",
    "invalidgifrandom": "/me [@%%NAME%%] Invalid request, try again.",


    "invalidtime": "/me [@%%NAME%%] Tempo especificado invalido.",
    "nouserspecified": "/me [@%%NAME%%] Nenhum usuario foi especificado.",
    "invaliduserspecified": "/me [@%%NAME%%] Usuario especificado invalido.",
    "nolistspecified": "/me [@%%NAME%%] Nenhuma lista especificada.",
    "invalidlistspecified": "/me [@%%NAME%%] Lista especificada invalida.",
    "novaliduserspecified": "/me [@%%NAME%%] Nenhum usuario valido especificado.",
    "nolimitspecified": "/me [@%%NAME%%] Nenhuma limite especificado.",
    "invalidlimitspecified": "/me [@%%NAME%%] Limite invalido.",
    "invalidpositionspecified": "/me [@%%NAME%%] Posição especificada invalida",
    "whois": "/me [%%NAME1%%] Nome de usuario: %%NAME2%%, ID: %%ID%%, Rank: %%RANK%%, Entrou: %%JOINED%%, Level: %%LEVEL%%, Linguagem: %%LANGUAGE%%, Avatar: %%AVATAR%%, Status: %%STATUS%%%%PROFILE%%",
    "toggleon": "/me [@%%NAME%%] %%FUNCTION%% habilitado.",
    "toggleoff": "/me [@%%NAME%%] %%FUNCTION%% desabilitado.",
    "cmddeletion": "command deletion",
    "afkremoval": "AFK removal",
    "afksremoved": "AFK's removed",
    "afklimit": "AFK limit",
    "autodisable": "autodisable",
    "autoskip": "autoskip",
    "newblacklisted": "/me [@%%NAME%%] This track belongs on the %%BLACKLIST%% blacklist! [ %%AUTHOR%% - %%TITLE%% - %%MID%% ]",
    "blinfo": "[@%%NAME%%] Blacklist Info - author: %%AUTHOR%%, title: %%TITLE%%, mid: %%SONGID%%",
    "blacklist": "blacklist",
    "cycleguard": "cycleguard",
    "timeguard": "timeguard",
    "chatfilter": "chatfilter",
    "historyskip": "historyskip",
    "lockdown": "lockdown",
    "lockguard": "lockguard",
    "usercommands": "usercommands",
    "motd": "MotD",
    "welcomemsg": "welcome message",
    "songstats": "song statistics",
    "etarestriction": "eta restriction",
    "voteskip": "voteskip",
    "voteskiplimit": "/me [@%%NAME%%] Voteskip limit is currently set to %%LIMIT%% mehs.",
    "voteskipexceededlimit": "/me @%%NAME%%, your song has exceeded the voteskip limit (%%LIMIT%% mehs).",
    "voteskipinvalidlimit": "/me [@%%NAME%%] Invalid voteskip limit, please try again using a number to signify the number of mehs.",
    "voteskipsetlimit": "/me [@%%NAME%%] Voteskip limit set to %%LIMIT%%.",
    "activeusersintime": "/me [@%%NAME%% There have been %%AMOUNT%% users chatting in the past %%TIME%% minutes.",
    "maximumafktimeset": "/me [@%%NAME%%] Maximum afk duration set to %%TIME%% minutes.",
    "afkstatusreset": "/me [@%%NAME%%] Reset the afk status of @%%USERNAME%%.",
    "inactivefor": "/me [@%%NAME%%] @%%USERNAME%% has been inactive for %%TIME%%.",
    "autowoot": "/me We recommend PlugCubed for autowooting: http://plugcubed.net/",
    "brandambassador": "/me A Brand Ambassador is the voice of the plug.dj users. They promote events, engage the community and share the plug.dj message around the world. For more info: https://plug.dj/ba",
    "bouncerplusrank": "/me [@%%NAME%%] You have to be manager or up to enable Bouncer+.",
    "chatcleared": "/me [@%%NAME%%] Cleared the chat.",
    "deletechat": "/me [@%%NAME%%] Cleared the chat of %%USERNAME%%.",
    "commandslink": "/me %%BOTNAME%% commands: %%LINK%%",
    "eatcookie": "/me eats a cookie.",
    "nousercookie": "/em doesn't see %%NAME%% in room and eats a cookie himself.",
    "selfcookie": "/me @%%NAME%%, you're a bit greedy, aren't you? Giving cookies to yourself, bah. Share some with other people!",
    "cookie": "/me @%%NAMETO%%, @%%NAMEFROM%% %%COOKIE%%",
    "cycleguardtime": "/me [@%%NAME%%] The cycleguard is set to %%TIME%% minute(s).",
    "dclookuprank": "/me [@%%NAME%%] Only bouncers and above can do a lookup for others.",
    "emojilist": "/me Emoji list: %%LINK%%",
    "notinwaitlist": "/me @%%NAME%%, you are not on the waitlist.",
    "eta": "/me @%%NAME%% you will reach the booth in approximately %%TIME%%.",
    "facebook": "/me Like us on facebook: %%LINK%%",
    "starterhelp": "/me This image will get you started on plug: %%LINK%%",
    "roulettejoin": "/me @%%NAME%% joined the roulette! (!leave if you regret it.)",
    "jointime": "/me [@%%NAMEFROM%%] @%%USERNAME%% has been in the room for %%TIME%%.",
    "kickrank": "/me [@%%NAME%%] you can't kick users with an equal or higher rank than you!",
    "kick": "/me [@%%NAME%%], @%%USERNAME%% you are being kicked from the community for %%TIME%% minutes.",
    "kill": "/me Desativando...",
    "logout": "/me [@%%NAME%%] Logging out %%BOTNAME%%",
    "rouletteleave": "/me @%%NAME%% left the roulette!",
    "songlink": "/me [@%%NAME%%] Link to current song: %%LINK%%",
    "usedlockskip": "/me [%%NAME%% used lockskip.]",
    "lockskippos": "/me [@%%NAME%%] Lockskip will now move the dj to position %%POSITION%%.",
    "lockguardtime": "/me [@%%NAME%%] The lockguard is set to %%TIME%% minute(s).",
    "maxlengthtime": "/me [@%%NAME%%] The maximum song duration is set to %%TIME%% minutes.",
    "motdset": "/me MotD set to:  %%MSG%%",
    "motdintervalset": "/me MotD interval set to %%INTERVAL%%.",
    "addbotwaitlist": "/me @%%NAME%%, por favor, não tente me adicionar á lista de espera.",
    "move": "/me [%%NAME%% used move.]",
    "mutednotime": "/me [@%%NAME%%] Mutou @%%USERNAME%%.",
    "mutedmaxtime": "/me [@%%NAME%%] You can only mute for maximum %%TIME%% minutes.",
    "mutedtime": "/me [@%%NAME%%] Muted @%%USERNAME%% for %%TIME%% minutes.",
    "unmuted": "/me [@%%NAME%%] Unmuted @%%USERNAME%%.",
    "muterank": "/me [@%%NAME%%] You can't mute persons with an equal or higher rank than you.",
    "oplist": "/me OP list: %%LINK%%",
    "pong": "/me Pong!",
    "reload": "/me Be right back.",
    "removenotinwl": "/me [@%%NAME%%] Specified user @%%USERNAME%% is not in the waitlist.",
    "roomrules": "/me Please find the room rules here: %%LINK%%",
    "sessionstats": "/me [@%%NAME%%] Total woots: %%WOOTS%%, total mehs: %%MEHS%%, total grabs: %%GRABS%%.",
    "skip": "/me [%%NAME%% used skip.]",
    "madeby": "/me This bot was made by %%NAME%%.",
    "activefor": "I have been active for %%TIME%%.",
    "swapinvalid": "/me [@%%NAME%%] Invalid user specified. (No names with spaces!)",
    "swapwlonly": "/me [@%%NAME%%] Please only swap users that are in the waitlist!",
    "swapping": "/me Swapping %%NAME1%% with %%NAME2%%.",
    "genres": "/me Please find the permissible room genres here: %%LINK%%",
    "notbanned": "/me [@%%NAME%%] The user was not banned.",
    "unmutedeveryone": "/me [@%%NAME%%] Unmuted everyone.",
    "unmuteeveryonerank": "/me [@%%NAME%%] Only managers and up can unmute everyone at once.",
    "notmuted": "/me [@%%NAME%%] that user wasn't muted.",
    "unmuterank": "/me [@%%NAME%%] You can't unmute persons with an equal or higher rank than you.",
    "commandscd": "/me [@%%NAME%%] The cooldown for commands by users is now set to %%TIME%% seconds.",
    "voteratio": "/me [@%%NAME%%] @%%USERNAME%% ~ woots: %%WOOT%%, mehs: %%MEHS%%, ratio (w/m): %%RATIO%%.",
    "website": "/me Please visit our website: %%LINK%%",
    "youtube": "/me [%%NAME%%] Subscribe to us on youtube: %%LINK%%",
    "songstatistics": "/me %%ARTIST%% - %%TITLE%%: %%WOOTS%%W/%%GRABS%%G/%%MEHS%%M.",
    "purchase": "/me [@%%NAME%%] Stock up on plug notes: https://plug.dj/purchase"
